# Generated by Django 3.2.13 on 2023-03-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='personal_account',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='Лицевой счёт'),
        ),
    ]
