# Generated by Django 3.2.13 on 2023-03-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230321_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Квартира'),
        ),
    ]
