# Generated by Django 3.2.13 on 2023-03-21 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date_create',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='request',
            name='type_request',
            field=models.CharField(max_length=100, null=True, verbose_name='Тип заявки'),
        ),
        migrations.AlterField(
            model_name='request',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.CreateModel(
            name='HomeOwnersAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('address_legal', models.CharField(max_length=255, verbose_name='Юр. адрес')),
                ('phone', models.CharField(max_length=13, verbose_name='Телефоный адрес')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='servicebill',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.homeownersassociation'),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
