# Generated by Django 3.2.13 on 2023-03-28 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230321_2241'),
        ('services', '0004_auto_20230322_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Горячая вода', 'Indicators Hot Water'), ('Холодная вода', 'Indicators Cold Water'), ('Дневной период', 'Indicators Light Day'), ('Ночной период', 'Indicators Light Night')], max_length=100, verbose_name='Показатель')),
            ],
        ),
        migrations.RemoveField(
            model_name='indicators',
            name='name',
        ),
        migrations.AddField(
            model_name='indicators',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.address'),
        ),
    ]
