# Generated by Django 3.2.13 on 2023-03-28 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20230328_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicators',
            name='couter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.counter'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='name',
            field=models.CharField(choices=[('Горячая вода', 'Indicators Hot Water'), ('Холодная вода', 'Indicators Cold Water'), ('Дневной период', 'Indicators Light Day'), ('Ночной период', 'Indicators Light Night')], max_length=100, unique=True, verbose_name='Показатель'),
        ),
    ]
